// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// gaussian_kernel_ratio
arma::vec gaussian_kernel_ratio(const arma::mat& x, const arma::mat& centers, double sigma, const arma::vec& kernel_weights, int n_threads);
RcppExport SEXP _UDID_gaussian_kernel_ratio(SEXP xSEXP, SEXP centersSEXP, SEXP sigmaSEXP, SEXP kernel_weightsSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type centers(centersSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type kernel_weights(kernel_weightsSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(gaussian_kernel_ratio(x, centers, sigma, kernel_weights, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// gaussian_kernel_matrix_bw
arma::mat gaussian_kernel_matrix_bw(const arma::mat& x, const arma::mat& centers, const arma::vec& sigma_vec, int n_threads);
RcppExport SEXP _UDID_gaussian_kernel_matrix_bw(SEXP xSEXP, SEXP centersSEXP, SEXP sigma_vecSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type centers(centersSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type sigma_vec(sigma_vecSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(gaussian_kernel_matrix_bw(x, centers, sigma_vec, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// gaussian_kernel_ratio_bw
arma::vec gaussian_kernel_ratio_bw(const arma::mat& x, const arma::mat& centers, const arma::vec& sigma_vec, const arma::vec& kernel_weights, int n_threads);
RcppExport SEXP _UDID_gaussian_kernel_ratio_bw(SEXP xSEXP, SEXP centersSEXP, SEXP sigma_vecSEXP, SEXP kernel_weightsSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type centers(centersSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type sigma_vec(sigma_vecSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type kernel_weights(kernel_weightsSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(gaussian_kernel_ratio_bw(x, centers, sigma_vec, kernel_weights, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// kliep_bw_cpp
Rcpp::List kliep_bw_cpp(const arma::mat& x1, const arma::mat& x2, const arma::mat& centers, arma::vec sigma_init, int n_y_cols, int fold, int n_cd_iter);
RcppExport SEXP _UDID_kliep_bw_cpp(SEXP x1SEXP, SEXP x2SEXP, SEXP centersSEXP, SEXP sigma_initSEXP, SEXP n_y_colsSEXP, SEXP foldSEXP, SEXP n_cd_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type x2(x2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type centers(centersSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type sigma_init(sigma_initSEXP);
    Rcpp::traits::input_parameter< int >::type n_y_cols(n_y_colsSEXP);
    Rcpp::traits::input_parameter< int >::type fold(foldSEXP);
    Rcpp::traits::input_parameter< int >::type n_cd_iter(n_cd_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(kliep_bw_cpp(x1, x2, centers, sigma_init, n_y_cols, fold, n_cd_iter));
    return rcpp_result_gen;
END_RCPP
}
// rowsums_grid_cpp
Rcpp::List rowsums_grid_cpp(const arma::mat& OR, const arma::mat& Cond, const arma::vec& Y_grid);
RcppExport SEXP _UDID_rowsums_grid_cpp(SEXP ORSEXP, SEXP CondSEXP, SEXP Y_gridSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type OR(ORSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Cond(CondSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Y_grid(Y_gridSEXP);
    rcpp_result_gen = Rcpp::wrap(rowsums_grid_cpp(OR, Cond, Y_grid));
    return rcpp_result_gen;
END_RCPP
}
// sens_rowsums_cpp
Rcpp::List sens_rowsums_cpp(const arma::mat& OR_grid, const arma::mat& Cond, const arma::vec& Y_grid, const arma::vec& mu_vec, double half_log_Gamma, bool is_UB);
RcppExport SEXP _UDID_sens_rowsums_cpp(SEXP OR_gridSEXP, SEXP CondSEXP, SEXP Y_gridSEXP, SEXP mu_vecSEXP, SEXP half_log_GammaSEXP, SEXP is_UBSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type OR_grid(OR_gridSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Cond(CondSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Y_grid(Y_gridSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mu_vec(mu_vecSEXP);
    Rcpp::traits::input_parameter< double >::type half_log_Gamma(half_log_GammaSEXP);
    Rcpp::traits::input_parameter< bool >::type is_UB(is_UBSEXP);
    rcpp_result_gen = Rcpp::wrap(sens_rowsums_cpp(OR_grid, Cond, Y_grid, mu_vec, half_log_Gamma, is_UB));
    return rcpp_result_gen;
END_RCPP
}
// mboot_sd_cpp
double mboot_sd_cpp(const arma::vec& V, int NumBoot);
RcppExport SEXP _UDID_mboot_sd_cpp(SEXP VSEXP, SEXP NumBootSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type V(VSEXP);
    Rcpp::traits::input_parameter< int >::type NumBoot(NumBootSEXP);
    rcpp_result_gen = Rcpp::wrap(mboot_sd_cpp(V, NumBoot));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_UDID_gaussian_kernel_ratio", (DL_FUNC) &_UDID_gaussian_kernel_ratio, 5},
    {"_UDID_gaussian_kernel_matrix_bw", (DL_FUNC) &_UDID_gaussian_kernel_matrix_bw, 4},
    {"_UDID_gaussian_kernel_ratio_bw", (DL_FUNC) &_UDID_gaussian_kernel_ratio_bw, 5},
    {"_UDID_kliep_bw_cpp", (DL_FUNC) &_UDID_kliep_bw_cpp, 7},
    {"_UDID_rowsums_grid_cpp", (DL_FUNC) &_UDID_rowsums_grid_cpp, 3},
    {"_UDID_sens_rowsums_cpp", (DL_FUNC) &_UDID_sens_rowsums_cpp, 6},
    {"_UDID_mboot_sd_cpp", (DL_FUNC) &_UDID_mboot_sd_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_UDID(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
