# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Fast Gaussian kernel density ratio evaluation
#'
#' Computes  r(x_i) = sum_c w_c * exp(-||x_i - center_c||^2 / (2*sigma^2))
#' for every row x_i of \code{x}.
#'
#' Drop-in replacement for:
#'   as.vector(densratio:::compute_kernel_Gaussian(x, centers, sigma) %*% kernel_weights)
#'
#' @param x              (N_eval x p)    evaluation points
#' @param centers        (N_centers x p) kernel centres from KLIEP fit
#' @param sigma          scalar          bandwidth
#' @param kernel_weights (N_centers)     weights from KLIEP fit
#' @param n_threads      int             OpenMP threads (0 = all; ignored without OpenMP)
#' @return numeric vector of length N_eval
gaussian_kernel_ratio <- function(x, centers, sigma, kernel_weights, n_threads = 0L) {
    .Call(`_UDID_gaussian_kernel_ratio`, x, centers, sigma, kernel_weights, n_threads)
}

#' Fast Gaussian kernel matrix with per-dimension bandwidths
#'
#' Computes  K_{i,c} = exp( - sum_j (x_{i,j} - center_{c,j})^2 / (2 * sigma_j^2) )
#' for every row i and every centre c.
#'
#' @param x        (N x p) evaluation points
#' @param centers  (M x p) kernel centres
#' @param sigma_vec (p)    per-dimension bandwidths
#' @param n_threads int    OpenMP threads (0 = all; ignored without OpenMP)
#' @return (N x M) kernel matrix
gaussian_kernel_matrix_bw <- function(x, centers, sigma_vec, n_threads = 0L) {
    .Call(`_UDID_gaussian_kernel_matrix_bw`, x, centers, sigma_vec, n_threads)
}

#' Fast Gaussian kernel density ratio evaluation with per-dimension bandwidths
#'
#' Computes  r(x_i) = sum_c w_c * exp( - sum_j (x_{i,j} - center_{c,j})^2 / (2 sigma_j^2) )
#'
#' @param x              (N_eval x p)    evaluation points
#' @param centers        (N_centers x p) kernel centres
#' @param sigma_vec      (p)             per-dimension bandwidths
#' @param kernel_weights (N_centers)     weights from KLIEP fit
#' @param n_threads      int             OpenMP threads (0 = all; ignored without OpenMP)
#' @return numeric vector of length N_eval
gaussian_kernel_ratio_bw <- function(x, centers, sigma_vec, kernel_weights, n_threads = 0L) {
    .Call(`_UDID_gaussian_kernel_ratio_bw`, x, centers, sigma_vec, kernel_weights, n_threads)
}

#' Full KLIEP with per-dimension bandwidth selection (all in C++)
#'
#' Runs coordinate-descent sigma search + KLIEP weight optimisation.
#' Drop-in replacement for KLIEP_bw() in R but much faster.
#'
#' @param x1         (n1 x p) numerator sample
#' @param x2         (n2 x p) denominator sample
#' @param centers    (M x p)  kernel centres
#' @param sigma_init (p)      starting bandwidths
#' @param n_y_cols   int      number of Y columns (get sigma_Y)
#' @param fold       int      CV folds
#' @param n_cd_iter  int      coordinate descent iterations
#' @return List with kernel_weights (vec), sigma (vec), centers (mat)
kliep_bw_cpp <- function(x1, x2, centers, sigma_init, n_y_cols, fold = 5L, n_cd_iter = 3L) {
    .Call(`_UDID_kliep_bw_cpp`, x1, x2, centers, sigma_init, n_y_cols, fold, n_cd_iter)
}

